"""venue: allowed_sport_id: FK

Revision ID: 1426d2c05b90
Revises: dc25dfb10108
Create Date: 2025-09-08 19:27:31.980658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1426d2c05b90'
down_revision: Union[str, Sequence[str], None] = 'dc25dfb10108'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('allowed_sport_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'venues', 'sports', ['allowed_sport_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venues', type_='foreignkey')
    op.drop_column('venues', 'allowed_sport_id')
    # ### end Alembic commands ###
