"""domain: sports/venues/courts/timeslots/bookings

Revision ID: dc25dfb10108
Revises: 8621195a29b2
Create Date: 2025-09-07 23:49:00.476222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc25dfb10108'
down_revision: Union[str, Sequence[str], None] = '8621195a29b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sports_name'), 'sports', ['name'], unique=True)
    op.create_table('venues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venues_name'), 'venues', ['name'], unique=False)
    op.create_table('courts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('sport_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('indoor', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('venue_id', 'name', name='uq_courts_venue_name')
    )
    op.create_index(op.f('ix_courts_sport_id'), 'courts', ['sport_id'], unique=False)
    op.create_index(op.f('ix_courts_venue_id'), 'courts', ['venue_id'], unique=False)
    op.create_table('timeslots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('court_id', sa.UUID(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('capacity > 0', name='ck_timeslots_capacity_positive'),
    sa.CheckConstraint('ends_at > starts_at', name='ck_timeslots_end_after_start'),
    sa.ForeignKeyConstraint(['court_id'], ['courts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('court_id', 'starts_at', 'ends_at', name='uq_timeslots_court_start_end')
    )
    op.create_index('ix_timeslots_court_start', 'timeslots', ['court_id', 'starts_at'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('timeslot_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['timeslot_id'], ['timeslots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'timeslot_id', name='uq_bookings_user_timeslot')
    )
    op.create_index('ix_bookings_timeslot', 'bookings', ['timeslot_id'], unique=False)
    op.create_index(op.f('ix_bookings_user_id'), 'bookings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_user_id'), table_name='bookings')
    op.drop_index('ix_bookings_timeslot', table_name='bookings')
    op.drop_table('bookings')
    op.drop_index('ix_timeslots_court_start', table_name='timeslots')
    op.drop_table('timeslots')
    op.drop_index(op.f('ix_courts_venue_id'), table_name='courts')
    op.drop_index(op.f('ix_courts_sport_id'), table_name='courts')
    op.drop_table('courts')
    op.drop_index(op.f('ix_venues_name'), table_name='venues')
    op.drop_table('venues')
    op.drop_index(op.f('ix_sports_name'), table_name='sports')
    op.drop_table('sports')
    # ### end Alembic commands ###
